[package]
name = "typst-uon"
version = "0.2.0"
entrypoint = "typst-uon.typ"
authors = ["Ian Knight <ian.knight2@nottingham.ac.uk>"]
license = "MIT"
description = "Colours and layouts for a consistent UoN document"
